FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY mvnw pom.xml ./
COPY .mvn .mvn

RUN ./mvnw dependency:go-offline

COPY . .

RUN ./mvnw clean package -DskipTests

CMD ["java", "-jar", "target/StudentsTool-0.0.1-SNAPSHOT.jar"]
